language: csharp
mono: none
dotnet: 1.1.0
dist: trusty
install:
- dotnet restore
script:
- dotnet build
- dotnet test CustomerAppBLLTests/CustomerAppBLLTests.csproj
notifications:
  email:
    on_success: never # default: change
    on_failure: change # default: always